# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GiphyApp', '0002_auto_20190207_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedgifs',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
